name: lmbench-snap
version: '0.1'
summary: lmbench test suit
description: |
  Snap of the lmbench program, having a series of micro 
  benchmarks designed to measure the basic operating 
  system and hardware system metrics.

grade: devel
confinement: devmode
base: core20        

architectures:
  - build-on: amd64
  - build-on: arm64

#apps:
#  lmbench-snap:
#   command: $SNAP/usr/bin/lmbench-run
#   environment: 
#     PATH: $SNAP/usr/:$PATH

parts:
  lmbench-snap:
    source: .
    plugin: nil
    #source-type: deb
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      #mkdir -p $SNAPCRAFT_PART_INSTALL/usr/include
      cp -r lmbench $SNAPCRAFT_PART_INSTALL/opt/  
      cp utils/script.sh $SNAPCRAFT_PART_INSTALL/opt/
      cp utils/info.md $SNAPCRAFT_PART_INSTALL/opt/
      snapcraftctl build
    build-packages:
     - libc6-dev
     - libc-dev
     - libc6
     - gcc
     - perl
     - build-essential
    stage-packages:
     - libc6-dev
     - libc-dev
     - libc6
     - gcc
     - perl
     - build-essential
     - make
